# Generated by Django 4.0.5 on 2022-07-21 02:30

import django.contrib.auth
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('01', 'Standard'), ('02', 'Standard with Playoffs'), ('03', 'Guess that Track')], default='01', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=django.contrib.auth.get_user_model, max_length=24)),
                ('points', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=80)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='leagues.round')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.player')),
            ],
        ),
    ]
