# Generated by Django 4.0.5 on 2022-07-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_player_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000023BAFD02680>', max_length=24),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
