# Generated by Django 4.0.5 on 2022-07-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
