# Generated by Django 4.0.5 on 2022-07-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='league1funtime', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('past', 'Expired Round'), ('current', 'Current Round'), ('future', 'Upcoming Round')], default='future', max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league'),
        ),
    ]
