# Generated by Django 4.0.5 on 2022-07-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_league_slug_round_status_alter_player_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league'),
        ),
    ]
