# Generated by Django 4.0.5 on 2022-07-28 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_remove_muzakuser_profile_img'),
        ('leagues', '0010_alter_player_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=24, null=True)),
                ('points', models.SmallIntegerField(default=0)),
                ('profile_img', models.ImageField(blank=True, upload_to='project/user_profiles/images')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(through='leagues.PlayerManager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='album_cover_url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='song',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='playermanager',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league'),
        ),
        migrations.AddField(
            model_name='playermanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.playermanager'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
