# Generated by Django 4.0.5 on 2022-07-29 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_playermanager_league_date_created_league_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='playermanager',
            name='league_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.round'),
        ),
    ]
