# Generated by Django 4.0.5 on 2022-08-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_rename_users_league_user_playermanager_league_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='song',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='playermanager',
            constraint=models.UniqueConstraint(fields=('user', 'league'), name='unique player'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('round', 'submitter'), name='one song per player'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('round', 'link'), name='unique song in round'),
        ),
        migrations.AlterModelTable(
            name='playermanager',
            table='leagues_playermanager',
        ),
        migrations.AlterModelTable(
            name='song',
            table='leagues_song',
        ),
    ]
