# Generated by Django 4.0.5 on 2022-08-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_rename_user_league_player_alter_song_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_cover_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
