# Generated by Django 4.0.5 on 2022-08-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_alter_song_album_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='leagues.round')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.playermanager')),
                ('target_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='leagues.song')),
            ],
            options={
                'db_table': 'leagues_vote',
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('round', 'submitter', 'target_song'), name='one vote per song, per player'),
        ),
    ]
